### ISSUE TITLE
Typescript dom reference causes failure in non-DOM contexts

### ISSUE THREAD

**Issue by ckknight** [sindresorhus/delay#40]
The lib reference to `dom` https://github.com/sindresorhus/delay/blob/34e50092c96d05f3d248130212a163a22570618f/index.d.ts#L1 prevents this from being properly usable within non-DOM contexts such as `react-native`.

```
node_modules/typescript/lib/lib.dom.d.ts:17604:6 - error TS2300: Duplicate identifier 'RequestInfo'.

17604 type RequestInfo = Request | string;
           ~~~~~~~~~~~

node_modules/@types/react-native/globals.d.ts:92:14
92 declare type RequestInfo = Request | string;
                ~~~~~~~~~~~
RequestInfo' was also declared here.
```

**Comment by sindresorhus** [comment]
@dex4er @felixfbecker How does one handle this? Is there any way we can just import exactly the symbols we need instead of all of the `dom`?

**Comment by felixfbecker** [comment]
Hmm, I'm not 100% sure. I think what other libraries like RxJS do is not include a triple-slash reference and instead require the consumer to add the `dom` lib if they want to use this feature. If not, the type of `signal` would simply be `any` I think, and it shouldn't cause errors as long as `skipLibCheck` is `true`.

Maybe TS people can give advice here? @RyanCavanaugh

**Comment by sindresorhus** [comment]
> instead require the consumer to add the dom lib if they want to use this feature.

That's very leaky. What if `delay` is used multiple levels deep?

> and it shouldn't cause errors as long as skipLibCheck is true.

This is also leaky.

---

In short, we shouldn't need to document TS specific config instructions to use this package.

**Comment by ckknight** [comment]
@felixfbecker:

`tsconfig.json`:
```json
{
  "compilerOptions": {
    "target": "es5",
    "module": "esnext",
    "allowJs": false,
    "sourceMap": true,
    "importHelpers": true,
    "downlevelIteration": true,
    "strict": true,
    "noImplicitAny": true,
    "strictNullChecks": true,
    "strictFunctionTypes": true,
    "strictPropertyInitialization": true,
    "noImplicitThis": true,
    "alwaysStrict": true,
    "noUnusedLocals": true,
    "noUnusedParameters": true,
    "noImplicitReturns": true,
    "noFallthroughCasesInSwitch": true,
    "moduleResolution": "node",
    "baseUrl": ".",
    "paths": {},
    "allowSyntheticDefaultImports": true,
    "esModuleInterop": true,
    "experimentalDecorators": true,
    "declarationMap": false,
    "jsx": "react-native",
    "lib": ["es2015", "es2016", "es2017", "es2018", "esnext.asynciterable"],
    "outDir": "dist",
    "rootDir": "./src"
  }
}
```

**Comment by felixfbecker** [comment]
I thought about the best solution for this and came up with https://github.com/sindresorhus/delay/pull/41

**Comment by RyanCavanaugh** [comment]
#41 is the correct way to handle this situation

**Comment by dex4er** [comment]
If the `delay` is a library that is mainly used in NodeJS, not a browser (see #30), then it shouldn't use any DOM features at all. That is my suggestion.

Simpler is better ™

**Comment by felixfbecker** [comment]
There is a difference between _using_ DOM features and _supporting_ DOM features. Especially if it’s possible to ponyfill.

**Comment by felixfbecker** [comment]
@dex4er "a lot of troubles and incompatibilities" is an over-exaggeration. There was a new feature added to `delay` in a major version. The way the typings were written caused errors in the new major version for TypeScript users with a certain tsconfig (a subset of the whole user base). Within a single day of the issue being reported there is a PR with a fix.

I wasn't aware `delay` is a library mainly for Node and don't seem anything indicating it is, nor a reason why it should be.

`AbortSignal` is not "non-standard". It's specced in the DOM standard, but that doesn't matter - so are many other things that can be used in Node too, like `URL` or `setTimeout`.

How exactly can this "conflict with other non-standard libraries"?

This feature is not a proof of concept. It is something that I am using in code that runs in the browser.

It's optional. You don't have to provide an AbortSignal. But if you have one, you can supply it now. And since it's an option, there is nothing preventing `delay` from also supporting other cancellation tokens in the future if TC39 specifies one too (although I don't see that happening anytime soon).
