### ISSUE TITLE
Add support for CommonJs

### ISSUE THREAD

**Issue by damartripamungkas** [sindresorhus/delay#58]
please add for support commonJs

**Comment by sindresorhus** [comment]
No plans for that.

https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by damartripamungkas** [comment]
> No plans for that.
> 
> https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

yes I know that, but ```await import(...)``` doesn't support compiling packages like ```vercel/pkg``` does

**Comment by jjangga0214** [comment]
@damartripamungkas He already decided and migrated many packages from CJS to pure ESM. 
Rolling back would not be an option from a realistic viewpoint..
It's a price to pay, and this discrepancy will make folks move to ESM faster, leading to the progress of the entire ecosystem.

If you need to use CJS without `import()`, then 

1. Use [timers-promises-api](https://nodejs.org/api/timers.html#timers-promises-api). 
2. Otherwise, just clone the `delay` package and convert it to CJS. It's just a single-file package.
